source "https://rubygems.org"
ruby "2.3.0"

gem "sinatra"
gem "sinatra-content-for", "~> 0.1"
gem "json"
gem "activesupport"
gem "i18n"
gem "flickraw"
gem "nokogiri"
# gem "yahoo-weather"

gem "rest-client"
gem "contest"
gem "sr-mg"
gem "redgreen"